### ISSUE TITLE
Close down API

### ISSUE THREAD

**Issue by Girgias** [neilime/php-css-lint#11]
Most methods/properties are declared as ``protected`` which I don't think should be the case as most of them work on its self and therefore should be declared ``private``.

I would also suggest to make the ``Linter`` class final and to add the ``private`` visibility to class constants (Available as of PHP 7.1, which this library already targets).

**Comment by neilime** [comment]
I prefer to use "protected" rather than private, in in order to allow overriding. This keep the source code "open"

**Comment by Girgias** [comment]
> I prefer to use "protected" rather than private, in in order to allow overriding. This keep the source code "open"

I'm usually not a fan of this as basically everything is part of the public API and can make changes difficult to execute :-(

But I understand the position so closing.
