### ISSUE TITLE
Take CSS in from STDIN

### ISSUE THREAD

**Issue by smileytechguy** [neilime/php-css-lint#2]
Hey,

I would like a way to potentially take input from STDIN.  As there is some PHP involved in the generation of my styles, I cannot reliably run automated tests on them using your library, however I like the fact that it is in PHP (and thus in composer).

Is there any way support for this option could be added?

**Comment by neilime** [comment]
Done : Version 1.1.0

**Comment by smileytechguy** [comment]
👍
