### ISSUE TITLE
Specify file indentation

### ISSUE THREAD

**Issue by petar-m-petrov** [neilime/php-css-lint#24]
I'm working with files that mostly have tabbed indentation. After digging through the code, I wasn't able to find a way of specifying the type of indentation in a file.

Is there such an option, and if not - will it be much of a hassle to implement?

**Comment by neilime** [comment]
I've made some changes in master branch : https://github.com/neilime/php-css-lint/wiki/Usage#allowed-indentation-chars
Does it fit your needs ?

**Comment by petar-m-petrov** [comment]
Wow! That's awesome - it works as expected, thank you.
