### ISSUE TITLE
Fails when testing with what appears to be a valid file

### ISSUE THREAD

**Issue by petar-m-petrov** [neilime/php-css-lint#25]
I've been trying to find a good PHP linter that checks if a CSS string has valid syntax. So far, this is the only one that has gotten the job almost right. My tests are done on the official stylesheet of [WordPress' **twentyseven** theme](https://wp-themes.com/twentyseventeen/) - [style.css](https://wp-themes.com/wp-content/themes/twentyseventeen/style.css). It returns a lot of errors, which I imagine shouldn't be flagged as such.

Here's the same file tested with the w3c's validator - [link](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwp-themes.com%2Fwp-content%2Fthemes%2Ftwentyseventeen%2Fstyle.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en).

Tested with latest version from **master** (before and after indentation update).

**Comment by neilime** [comment]
I'll check what's wrong with the linter on the next few days
