### ISSUE TITLE
Inject Properties class into Linter to respect Dependency Inversion principle

### ISSUE THREAD

**Issue by Girgias** [neilime/php-css-lint#9]
Currently the ``Properties`` class is not declared as ``final`` but it's impossible to inject an extended class of it into the Linter.

For this I would propose to add a constructor to ``Linter`` and remove the ``getCssLintProperties()`` method.

**Comment by neilime** [comment]
I've added a constructor to Linter, that accept an optional instance of the "\CssLint\Properties" helper (Version 2.1.0)
